###
### Hugo configuration
###
### Ref. https://gohugo.io/getting-started/configuration
###

baseURL: "https://waltlenu.it"
title: "waltlenu.it"

# Locale
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    contentDir: content/en
    disabled: false
    languageCode: en-GB
    languageDirection: ltr
    languageName: English
    weight: 1
    menu:
      main:
        - identifier: about
          name: about
          url: /about
          weight: 1
        - identifier: blog
          name: blog
          url: /blog
          weight: 2
  it:
    contentDir: content/it
    disabled: true
    languageCode: it-IT
    languageDirection: ltr
    languageName: Italiano
    weight: 2

# Taxonomies
# Ref. https://gohugo.io/content-management/taxonomies
taxonomies: {}

# Formats
outputs:
  home:
    - html
    - amp
    - rss
    - json # necessary for search
  page:
    - html
    - amp

# When building, removes files from destination not found in static directories
cleanDestinationDir: true

# Enable Emoji emoticons support for page content
enableEmoji: true

# Install PaperMod theme as golang module
module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod

# Parameters (mostly used by PaperMod)
params:
  keywords: [Blog, Homepage, Portfolio]
  author: "Walter Lenuzza"
  description: "Walter Lenuzza's homepage"

  # PaperMod theme profile-mode
  profileMode:
    enabled: true
    title: "Walter Lenuzza"
    subtitle: "Platform Engineer"
    imageUrl: "avatar.webp"
    imageTitle: "Walter Lenuzza avatar"
    buttons:
      - name: About
        url: about
      - name: Blog
        url: blog

  socialIcons:
    - name: linkedin
      url: "https://uk.linkedin.com/in/waltlenu"
    - name: github
      url: "https://github.com/waltlenu"
    - name: bluesky
      url: "https://bsky.app/profile/waltlenu.it"

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
