baseurl = "https://waltlenu.it"
title = "waltlenu.it"
languagecode = "en"
defaultcontentlanguage = "en"

theme = "coder"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Walter Lenuzza"
    description = "NeoCortex Cold Storage"
    keywords = "blog,personal,sysadmin,devops,developer"
    info = "Senior Devops Consultant"
    avatarurl = "avatar.jpg"
    footercontent = "Hi, I'm a footer message!"

    dateformat = "January 2, 2006"

    hideFooter = true
    hideCredits = false
    hideCopyright = false
    since = 2017

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "dark"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about"

            [[languages.en.menu.main]]
            name = "Posts"
            weight = 2
            url = "posts"

            [[languages.en.menu.main]]
            name = "Tags"
            weight = 3
            url = "tags"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 4
            url = "categories/blog"

            [[languages.en.menu.main]]
            name = "Notes"
            weight = 5
            url = "categories/notes"


[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/waltlenu"

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/waltlenu"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://uk.linkedin.com/in/waltlenu"

[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 6
    url = "https://waltlenu.it/index.xml"
    rel = "alternate"
    type = "application/rss+xml"

# disqusShortname = "yourdiscussshortname"

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
#     siteID = "ABCDE"
#     # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#     serverURL = "analytics.example.com"