baseURL = "https://waltlenu.it"
title = "waltlenu.it - NeoCortex Cold Storage"

defaultContentLanguage = "en"
languageCode = "en-us"
theme = "simplicity"

enableEmoji = true
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsStyle = "native"
pygmentsUseClasses =  true

disqusShortname = "test"
googleAnalytics = ""

[author]
  gravatarEmail = "test@example.com"
  homepageText = "waltlenu.it - NeoCortex Cold Storage"
  name = "Walter `waltlenu` Lenuzza"
  rss = "/posts/index.xml"
[imaging]
  anchor = "smart"
  resampleFilter = "box"
  quality = 75
[[menu.pages]]
  name = "Projects"
  weight = -100
  identifier = "projects"
  url = "/projects/"
[[menu.pages]]
  name = "Photos"
  weight = -90
  identifier = "photos"
  url = "/photos/"
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
[params]
  adsenseClient = ''
  adsenseSlot = ''
  description = "NeoCortex Cold Storage"
  licence = "[Some Rights Reserved](http://creativecommons.org/licenses/by-sa/4.0/)."
  displayPostLanguage = true
[permalinks]
  posts = "/:year/:month/:day/:slug/"
[pygmentsOptions]
  linenos = false
