baseurl = "https://waltlenu.it"
defaultcontentlanguage = "en"
languagecode = "en"
title = "waltlenu.it"

theme = "coder"

canonifyurls = true
paginate = 20
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "b2"

[params]
author = "Walter Lenuzza"
avatarurl = "avatar.jpg"
description = "NeoCortex Cold Storage"
footercontent = "Hi, I'm a hidden footer message!"
info = "Senior Devops Consultant"
keywords = "blog,personal,sysadmin,devops,developer"

dateformat = "January 2, 2006"

hideCopyright = false
hideCredits = false
hideFooter = true
since = 2017

# Git Commit in Footer, uncomment the line below to enable it.
commit = "https://github.com/luizdepra/hugo-coder/tree/"

rtl = false

# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorscheme = "dark"

# Series see also post count
maxSeeAlsoItems = 5

# Custom CSS
custom_css = []

# Custom JS
custom_js = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[languages]
[languages.en]
languagename = "English"

[languages.en.menu]

[[languages.en.menu.main]]
name = "About"
url = "about"
weight = 1

[[languages.en.menu.main]]
name = "Posts"
url = "posts"
weight = 2

[[languages.en.menu.main]]
name = "Tags"
url = "tags"
weight = 3

[[languages.en.menu.main]]
name = "Blog"
url = "categories/blog"
weight = 4

[[languages.en.menu.main]]
name = "Notes"
url = "categories/notes"
weight = 5

[[params.social]]
icon = "fab fa-github"
name = "Github"
url = "https://github.com/waltlenu"
weight = 1

[[params.social]]
icon = "fab fa-twitter"
name = "Twitter"
url = "https://twitter.com/waltlenu"
weight = 3

[[params.social]]
icon = "fab fa-linkedin"
name = "LinkedIn"
url = "https://uk.linkedin.com/in/waltlenu"
weight = 4

[[params.social]]
icon = "fas fa-rss"
name = "RSS"
rel = "alternate"
type = "application/rss+xml"
url = "https://waltlenu.it/index.xml"
weight = 6

# disqusShortname = "yourdiscussshortname"

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
#     siteID = "ABCDE"
#     # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#     serverURL = "analytics.example.com"
