###
### Hugo configuration
###
### Ref. https://gohugo.io/getting-started/configuration
###

buildDrafts: true
buildFuture: true
buildExpired: true

enableRobotsTXT: false

minify:
  minifyOutput: false

params:
  # disable google analytics, opengraph, twitter-cards and schema
  env: development
