###
### Hugo configuration
###
### Ref. https://gohugo.io/getting-started/configuration
###

enableRobotsTXT: true

# Minification
minify:
  disableXML: true
  minifyOutput: true

params:
  # enable opengraph, twitter-cards and schema
  env: production
